# Generated by Django 5.0.4 on 2024-05-15 11:22

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='com_static_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=150)),
                ('com_type', models.CharField(max_length=250)),
                ('com_revenue', models.IntegerField()),
                ('com_net_income', models.IntegerField()),
                ('news_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='news_title', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='com_var_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sh_price', models.IntegerField()),
                ('sh_volume', models.IntegerField()),
            ],
        ),
    ]
