# Generated by Django 5.0.4 on 2024-05-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_com_static_data_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com_static_data',
            name='com_net_income',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='com_static_data',
            name='com_revenue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='com_var_data',
            name='sh_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='com_var_data',
            name='sh_volume',
            field=models.FloatField(),
        ),
    ]
